# Go Dep
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#version-rules

# Test dependencies
# -----------------------------------------------------------
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/bouk/monkey"
  revision = "5df1f207ff77e025801505ae4d903133a0b4353f"

# General dependencies
# -----------------------------------------------------------
[[constraint]]
  name = "github.com/phR0ze/n"
  version = "~1.0.77"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.3"

# General directives
# -----------------------------------------------------------
[prune]
  non-go = true
  go-tests = true
  unused-packages = true
